### PR TITLE
[PR] The proj files have been updated to enable SourceLink

### PR DESCRIPTION
**Pull request by JTOne123**
CSProj files have been updated to enable SourceLink in your nuget
---

*[This pull request was created with an automated workflow]*

I noticed that your repository and Nuget package are important for our .NET community, but you still haven't enabled SourceLink.

**We have to take 2 steps:**
1) Please approve this pull request and make .NET a better place for .NET developers and their debugging.
2) **Then just upload the .snupkg file** to https://www.nuget.org/ (now you can find the snupkg file along with the .nuget file)

You can find more information about SourceLine at the following links  
https://github.com/dotnet/sourcelink
https://www.hanselman.com/blog/ExploringNETCoresSourceLinkSteppingIntoTheSourceCodeOfNuGetPackagesYouDontOwn.aspx

If you are interesting about this automated workflow and how it works  
https://github.com/JTOne123/GitHubMassUpdater

*If you notice any flaws, please comment and I will try to make fixes manually*

### CODE REVIEW

**Comment by goofballLogic** [comment]
@asbjornu @wattsm any knowledge of this system? I've not encountered it before... If it's becoming a standardised .NET way of working then I'm supportive but I think we should steer away from proprietary tools/frameworks/systems which have any potential to introduce barriers to usage.

**Comment by asbjornu** [comment]
I think this is a nice addition, but I would love to revisit this once #58 is complete, since then we have in place a method to actually publish the sources to NuGet (automatically).

**Comment by goofballLogic** [comment]
pending #58

**Comment by asbjornu** [comment]
#58 is now merged, so a rebase against the `HEAD` of `master` would be appreciated. Also please have a look at the GitHub Actions workflow to see if any adjustments are needed there in order for SourceLink to work as intended.

**Comment by asbjornu** [comment]
@JTOne123 ping?

**Comment by JTOne123** [comment]
Sorry, I don't have time to fix it now. So please feel free to do it by yourself or just close the PR

**Pull request closed without merging**
