### PR TITLE
Add release workflow

### PR DESCRIPTION
**Pull request by asbjornu**
This adds a release workflow that will add to the existing test workflow, which in total should make the CI/CD pipeline look like this:

1. Pull requests are tested with various tools and reported with GitHub Checks so it's easy to see the condition of a PR.
2. All pull requests need to be reviewd by a code owner (see #61).
3. When a PR has all green checks and an approved review, it will be merged to `master`.
4. All commits to `master` will invoke the release pipeline to release a pre-release package to the GitHub Package Registry.
5. Once we are happy with the state of `master` a maintainer creates a new GitHub Release versioned according to [SemVer 2.0](https://semver.org/).
6. The release will also create a tag, which will invoke a new release workflow, this time for a stable release to NuGet.org.

Thoughts, comments and general feedback is welcome.

### CODE REVIEW

**Comment by goofballLogic** [comment]
Can we open an issue for this to discuss the principles we're aiming for. Is it related to #60 ?

**Comment by asbjornu** [comment]
> Can we open an issue for this to discuss the principles we're aiming for. Is it related to #60 ?

Even if we decide to do a rewrite, having a working CI/CD pipeline is going to be a requirement. So getting this up in working order and merged would benefit a greenfield codebase just as much as the current one.

**Comment by asbjornu** [comment]
@goofballLogic, in https://github.com/linked-data-dotnet/json-ld.net/issues/60#issuecomment-653385861 you asked:

> Is there anything you can use help with on #58 ?

Indeed it is. I haven't spent much time trying to figure this one out, but currently [the build is failing at the `NuGet Pack` step](https://github.com/linked-data-dotnet/json-ld.net/pull/58/checks?check_run_id=809023625) with the following exception:

```
##[error]/opt/hostedtoolcache/dncs/2.1.401/x64/sdk/2.1.401/Sdks/NuGet.Build.Tasks.Pack/buildCrossTargeting/NuGet.Build.Tasks.Pack.targets(199,5): error NU5026: The file '/home/runner/work/json-ld.net/json-ld.net/src/json-ld.net/bin/Debug/netcoreapp2.1/json-ld.net.dll' to be packed was not found on disk. [/home/runner/work/json-ld.net/json-ld.net/src/json-ld.net/json-ld.net.csproj]
##[error]Process completed with exit code 1.
```

If anyone can assist in figuring out why `/home/runner/work/json-ld.net/json-ld.net/src/json-ld.net/bin/Debug/netcoreapp2.1/json-ld.net.dll` is missing (or how it can be excluded from consideration by `dotnet pack` if it shouldn't be existing), that would be very helpful.

**Comment by goofballLogic** [comment]
done #64

**Comment by asbjornu** [comment]
This won't be tested properly until it's merged to `master` and we tag a commit, which I suggest we do soon as it's quite a while since the last release. I'll of course fix problems that arise during the next release.

**Comment by goofballLogic** [comment]
Happy to merge on that basis.

**Review by goofballLogic — APPROVED** [review]

**Pull request merged**
